name: Deploy Chocolateria to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -e
            cd /var/www/codicoffee.com/chocolateria
            git fetch origin master
            git reset --hard origin/master
            npm ci
            npm run build
            echo "✅ Chocolateria deployed successfully on $(date)"